set(_CATKIN_CURRENT_PACKAGE "image_tutorials")
set(image_tutorials_VERSION "0.0.0")
set(image_tutorials_MAINTAINER "Your Name <you@yourdomain.tld>")
set(image_tutorials_PACKAGE_FORMAT "1")
set(image_tutorials_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "cv_bridge")
set(image_tutorials_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(image_tutorials_BUILDTOOL_DEPENDS "catkin")
set(image_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(image_tutorials_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(image_tutorials_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(image_tutorials_TEST_DEPENDS )
set(image_tutorials_DOC_DEPENDS )
set(image_tutorials_DEPRECATED "")